export const actionTypes = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
};
